GEMINI_API_KEY = "AIzaSyCvIyif0BlqvENV31FaNBC0mzuN3K-_WSw"
SERPER_API_KEY = "46b95dbe2c21affea854a43ad1f52b95bd74b234"
OPENAI_API_KEY = "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"